### ISSUE TITLE
Only want to say thank you ;-)

### ISSUE THREAD

**Issue by giovanne123** [Tob1as/docker-mariadb#10]
Hi Tobias,
I only want to say thanks you!

I'm using your image/container on a Raspberry Pi 4 with armv7.
Because there was no newer MariaDB than 10.5.15 in OS packager (agt-get), I switched to MariaDB in Container/Docker.
And because there is no official image for armv7, you "saved my life" ;-)
I'm using it for Home Assistant also running in Docker Container. 

So far it is running without issues...

Thanks and would be fine if you continued maintaining it!

**Comment by Tob1as** [comment]
Hello,
thanks for your feedback :smiley:

(There is one alternative ([Docker-Hub](https://hub.docker.com/r/linuxserver/mariadb)|[GitHub](https://github.com/linuxserver/docker-mariadb)) :wink:, but I have not yet tested it myself.)

**Comment by giovanne123** [comment]
Thanks, yes I already saw this too. It has a little bit different structure for config/ databases but was running in general.
At the beginning I had some trouble (with linuxserver-mariadb) when new Home Assistant migrated old DB to new one. But the I think the reason maybe was my DB size.
I had minimized my HA DB (by minimize Recorder purge keep days) and same time switched to your MariaDB and it was directly working ;-)
So would be fine if you maintain it - but so far it is working....

Btw: Do you know, if I copy my DB/Data folder to same version from linuxserver-mariadb should it be running or do I always have to dump&import between different distributors?

**Comment by Tob1as** [comment]
I would always recommend a dump&import, whatever you need:
```sh
# dump all databases
mysqldump --host=localhost --port=3306 --user=root --password=${MARIADB_ROOT_PASSWORD} --all-databases | gzip -9 > ./mariadb_backup.sql.gz
# dump specific database
mysqldump --host=localhost --port=3306 --user=${MARIADB_USER} --password=${MARIADB_PASSWORD} --databases ${MARIADB_DATABASE} | gzip -9 > ./mariadb_backup_${MARIADB_DATABASE}.sql.gz
```

**Comment by Tob1as** [comment]
I update/rebuild the 10.5 image(s).... when you use TAG 10.5 (debian) then use in futur 10.5-debian  :wink:

**Note**: However, I have only performed a simple functional test. So please make a backup before changing.

**Comment by giovanne123** [comment]
Thanks, but I am already using: tobi312/rpi-mariadb:10.6-debian

Working fine since two weeks for usage with Home Assistant :-)

**Comment by Tob1as** [comment]
okay.... I just noticed that version 10.6 from Debian [bookworm](https://packages.debian.org/bookworm/mariadb-server) has been replaced by 10.11....So I can't update 10.6 in Debian image anymore.  
The stable version [10.11](https://mariadb.com/kb/en/release-notes-mariadb-1011-series/) was released in februrar as new LTS.

**Comment by giovanne123** [comment]
Ok thanks for the info.
Two weeks ago I was pointed to this https://endoflife.date/mariadb and thought to have 3years now :-)

But, 
I will follow what HA recommends in the next releases.... 

And I can prepare myself to possibility switch to 10.11...
